### DISCUSSION TITLE
Experimental Tailwind 4 Support?

### DISCUSSION THREAD

**Discussion by sveltecult** [franken-ui/ui#65] [Ideas]
I must admit that I was frustrated with the demise of `tailwind.config.js`, along with `safelist` and `preset`. Our entire library relies heavily on these features. Having JavaScript as a config is very powerful, as it allows us to perform complex computations compared to just using CSS. However, we need to adapt to the changes.

First, let's discuss why we need computation in the first place. Why can't we just paste our customizations, colors, and other settings into our `app.css` file? If you've been with us since the beginning, you're probably aware of the reason. For those who aren't, it's because we're converting HSL to hex, injecting them into SVG tags, and making them inline. We then use these SVGs as background images, which allows us to use checkboxes and radios as intended. React, Svelte, and Vue ports, on the other hand, hack radios and checkboxes by using buttons instead of the correct HTML tags, enabling them to dynamically change colors. Note that we strive to be as HTML-compliant as possible, so that method isn't viable for us.

As I've mentioned before, Tailwind CSS is optional. Last night, I had an "Aha!" moment that might solve our computation dilemma. Instead of being a Tailwind CSS plugin, we can move the computation to Vite.

First, update to `franken-ui@internal.43`.

Now, if you're using Tailwind v4, your `app.css` file will now look like this:

```css
@import 'tailwindcss';

@theme {
	--color-background: hsl(var(--background));
	--color-foreground: hsl(var(--foreground));
	--color-muted: hsl(var(--muted));
	--color-muted-foreground: hsl(var(--muted-foreground));
	--color-card: hsl(var(--card));
	--color-card-foreground: hsl(var(--card-foreground));
	--color-popover: hsl(var(--popover));
	--color-popover-foreground: hsl(var(--popover-foreground));
	--color-border: hsl(var(--border));
	--color-input: hsl(var(--input));
	--color-primary: hsl(var(--primary));
	--color-primary-foreground: hsl(var(--primary-foreground));
	--color-secondary: hsl(var(--secondary));
	--color-secondary-foreground: hsl(var(--secondary-foreground));
	--color-accent: hsl(var(--accent));
	--color-accent-foreground: hsl(var(--accent-foreground));
	--color-destructive: hsl(var(--destructive));
	--color-destructive-foreground: hsl(var(--destructive-foreground));
	--color-ring: hsl(var(--ring));

	--font-geist-sans: Geist Sans, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
		'Segoe UI Emoji', Segoe UI Symbol, 'Noto Color Emoji';
	--font-geist-mono: Geist Mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
		'Liberation Mono', 'Courier New', monospace;
}

@layer base {
	/* @import 'franken-ui/css/custom-palette.css'; */

	@import 'franken-ui/css/npf.css';
}
```

As you can see, we're importing `npf.css`, which is a trimmed-down version of the entire Franken UI CSS, excluding preflight and pre-bundled color utilities.

To customize your color palette (add branding), simply update your `vite.config.js` file to use our Vite plugin:

```js
import franken from 'franken-ui/plugin-vite';
import tailwindcss from '@tailwindcss/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [
		sveltekit(),
		franken({
			customPalette: {
				'.uk-theme-emerald': {
					'--background': '160.1 100% 95%',
					'--foreground': '160.1 5% 10%',
					'--card': '160.1 50% 90%',
					'--card-foreground': '160.1 5% 15%',
					'--popover': '160.1 100% 95%',
					'--popover-foreground': '160.1 100% 10%',
					'--primary': '160.1 84.1% 39.4%',
					'--primary-foreground': '0 0% 100%',
					'--secondary': '160.1 30% 70%',
					'--secondary-foreground': '0 0% 0%',
					'--muted': '122.1 30% 85%',
					'--muted-foreground': '160.1 5% 35%',
					'--accent': '122.1 30% 80%',
					'--accent-foreground': '160.1 5% 15%',
					'--destructive': '0 100% 30%',
					'--destructive-foreground': '160.1 5% 90%',
					'--border': '160.1 30% 50%',
					'--input': '160.1 30% 26%',
					'--ring': '160.1 84.1% 39.4%'
				},
				'.dark.uk-theme-emerald': {
					'--background': '160.1 50% 10%',
					'--foreground': '160.1 5% 90%',
					'--card': '160.1 50% 10%',
					'--card-foreground': '160.1 5% 90%',
					'--popover': '160.1 50% 5%',
					'--popover-foreground': '160.1 5% 90%',
					'--primary': '160.1 84.1% 39.4%',
					'--primary-foreground': '0 0% 100%',
					'--secondary': '160.1 30% 20%',
					'--secondary-foreground': '0 0% 100%',
					'--muted': '122.1 30% 25%',
					'--muted-foreground': '160.1 5% 60%',
					'--accent': '122.1 30% 25%',
					'--accent-foreground': '160.1 5% 90%',
					'--destructive': '0 100% 30%',
					'--destructive-foreground': '160.1 5% 90%',
					'--border': '160.1 30% 26%',
					'--input': '160.1 30% 26%',
					'--ring': '160.1 84.1% 39.4%'
				}
			}
		}),
		tailwindcss()
	]
});
```

Make sure to uncomment the `@import 'franken-ui/css/custom-palette.css';` line in your `app.css` file.

Theoretically, everything should work with only one caveat: Tailwind Intellisense will not be available for `uk-*` classes. If you're using Tailwind CSS v3 or have installed it via CDN, you won't have any changes.

I have publish a sample [SvelteKit template](https://github.com/franken-ui/template-sveltekit) that you can refer to. Please help yourself and the community by reporting any issues you encounter, as I haven't fully tested this yet. As I've mentioned, we don't use Tailwind v4, so my test cases are limited.

Video Demo:

https://github.com/user-attachments/assets/234c3562-8422-4f61-967d-bbda5209b5fc
