### ISSUE TITLE
Incorrect background color opacity

### ISSUE THREAD

**Issue by Teraskull** [franken-ui/ui#47]
Hi,

Noticed that the destructive button background color does not match the shadcn color on hover.

shadcn:
![image](https://github.com/user-attachments/assets/ab831ea5-0895-46c3-a7e7-121b8df15706)

franken-ui:
![image](https://github.com/user-attachments/assets/a87bd702-160c-440d-80f6-013b44a4614d)

I assume this is unintentional, as all other Zinc theme colors and CSS variables seem to match the shadcn colors.

This happens in both version 1 and 2.

In version 1:
```css
.uk-button-danger:hover {
    opacity: .9;
}
```

In version 2:
```css
.uk-btn:hover {
    opacity: .8;
}
```

Shadcn does this, instead of just `opacity`:
```css
.hover\:bg-destructive\/90:hover {
    background-color: hsl(var(--destructive) / .9);
}
```

But for the secondary button background color, shadcn uses 80% opacity:
```css
.hover\:bg-secondary\/80:hover {
    background-color: hsl(var(--secondary) / .8);
}
```

Which means `.uk-btn` cannot have the same hover opacity for all buttons, since they differ.

I know this is a very minor nitpick, but I thought maybe this issue was missed.

Thanks for the great work!
