### ISSUE TITLE
cursor: pointer not applied to buttons

### ISSUE THREAD

**Issue by edxeth** [franken-ui/ui#88]
When hovering over buttons in my project, the mouse cursor does not change to a pointer (hand icon) as users would typically expect. Instead, it stays as the default arrow cursor. This makes it less clear that the buttons are clickable.

**To Reproduce**

- Set up a project with Vite 6.3.2, Tailwind CSS 4.1.4, and Franken UI 2.1.0-next.4
- Import Franken UI JS modules as shown below:

```js
// src/js/core.js
import "franken-ui/js/core.iife";

// src/js/icon.js
import "franken-ui/js/icon.iife";
```

- Import styles as shown below:

```css
/* src/css/globals.css */
@import "tailwindcss";

@source "../views/**/*";

@custom-variant dark (&:where([data-theme=dark], [data-theme=dark] *));

@theme {
  --color-background: hsl(var(--background));
  --color-foreground: hsl(var(--foreground));
  --color-muted: hsl(var(--muted));
  --color-muted-foreground: hsl(var(--muted-foreground));
  --color-card: hsl(var(--card));
  --color-card-foreground: hsl(var(--card-foreground));
  --color-popover: hsl(var(--popover));
  --color-popover-foreground: hsl(var(--popover-foreground));
  --color-border: hsl(var(--border));
  --color-input: hsl(var(--input));
  --color-primary: hsl(var(--primary));
  --color-primary-foreground: hsl(var(--primary-foreground));
  --color-secondary: hsl(var(--secondary));
  --color-secondary-foreground: hsl(var(--secondary-foreground));
  --color-accent: hsl(var(--accent));
  --color-accent-foreground: hsl(var(--accent-foreground));
  --color-destructive: hsl(var(--destructive));
  --color-destructive-foreground: hsl(var(--destructive-foreground));
  --warning: hsl(var(--warning));
  --warning-foreground: hsl(var(--warning-foreground));
  --color-ring: hsl(var(--ring));
}

@import 'franken-ui/css/franken-ui.css';
```

- Use `preflight: false` in `vite.config.js`

- Hover over any button component in the UI

**Expected behavior**

When hovering over a button, the cursor should change to a pointer to indicate interactivity.

**Actual behavior**

The cursor remains as the default arrow, not a pointer.

**Screenshot**

![Image](https://github.com/user-attachments/assets/3417ada1-19a2-4cdf-9091-7e4640ed2a2d)
